security:
    basic:
        enabled: false
        path: /**
        realm: Spring
    enable-csrf: false
    headers:
        cache: false
        content-type: false
        frame: false
        hsts: all
        xss: false
    ignored: /**/**
    require-ssl: false
    sessions: stateless
    user:
        name: user
        password: ''
        role: USER
server:
    port: 8080
    session-timeout: 600
    tomcat:
        access-log-enabled: true
        access-log-pattern: common
        background-processor-delay: 30
        basedir: /tmp
        max-threads: 0
        protocol-header: x-forwarded-proto
        remote-ip-header: x-forwarded-for
        uri-encoding: UTF-8
spring:
    dao:
        exceptiontranslation:
            enabled: true
    data:
        jpa:
            repositories:
                enabled: true
    datasource:
        continue-on-error: false
        data: data.sql
        driverClassName: com.mysql.jdbc.Driver
        initial-size: 10
        initialize: false
        jmx-enabled: false
        max-active: 100
        max-idle: 8
        max-wait: 300
        min-evictable-idle-time-millis: 3000
        min-idle: 8
        name: datasource
        password: cs105221791
        platform: mysql
        schema: schema.sql
        separator: ;
        sql-script-encoding: utf-8
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 3000
        url: jdbc:mysql://qdm112529519.my3w.com:3306/qdm112529519_db?useUnicode=true&characterEncoding=UTF-8
        username: qdm112529519
        validation-query: select 1
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        open-in-view: true
        show-sql: true
    messages:
        basename: messages
        cache-seconds: -1
        encoding: UTF-8
    redis:
        database: 0
        host: 0o0o0o.cn
        password: ''
        port: 6379
    thymeleaf:
        cache: false
        check-template-location: true
        content-type: text/html
        encoding: UTF-8
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
com:
    learning:
        gcs:
            gateway:
                scheduleToggle: enable